### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by AbleLincoln** [flywebguy/tea-cozy#3]
I'm curious as to why you added opacity: 0.9 to the body. Are you aware that this makes _every_ element have opacity 0.9? If you were trying to change the opacity of the background color of the body, there are better ways to do that. For instance you could use rgba color values. If you want to read more about rgba colors check [here](https://www.w3schools.com/css/css3_colors.asp)

https://github.com/flywebguy/tea-cozy/blob/master/resources/css/style.css#L7

**Comment by flywebguy** [comment]
@AbleLincoln I didn't pay close attention to my placement when reviewing the redline mockup and accidentally added it to the body. Thanks for pointing that out!
