### ISSUE TITLE
Interesting choice

### ISSUE THREAD

**Issue by AbleLincoln** [flywebguy/tea-cozy#5]
The mission image wasn't supposed to be full-width, but I like the change you made. I actually think yours looks better

https://github.com/flywebguy/tea-cozy/blob/master/resources/css/style.css#L64

**Comment by flywebguy** [comment]
@AbleLincoln you're right. I didn't even catch that it wasn't suppose to be full-width. 99% of the time with my freelance client work, I have that request for masthead/splash images, so did it without thinking. I should have paid closer attention to the specs!
